# Paths
staging_folder: "outputs/models/staging/"
model_pickle_local_path: "outputs/models/staging/model.pickle"
model_evaluation_folder: "outputs/model_evaluation/"

### CPI DATA ###
cpi_data:
  cpi_column_header: "CPI INDEX 05.3 : Household appliances, fitting and repairs 2015=100"
  cpi_source_url: "https://www.ons.gov.uk/generator?format=csv&uri=/economy/inflationandpriceindices/timeseries/d7ck/mm23"
  cpi_reference_year: 2024

### LOCATION DATA ###
# Location data source links available a few lines down; downloaded data is stored in S3 as per line below
location_data_s3_dir: "s3://asf-hp-cost-estimator-model/inputs/location_data/"

# Postcode to OA (2021) to LSOA to MSOA to LAD (November 2024) Best Fit Lookup in the UK
# Link: https://open-geography-portalx-ons.hub.arcgis.com/datasets/068ee476727d47a3a7a0d976d4343c59/about
postcode_to_lad_census_2021_filename: "PCD_OA21_LSOA21_MSOA21_LAD_NOV24_UK_LU.csv"

# Local Authority District to Region (December 2024) Lookup in EN
# Link: https://geoportal.statistics.gov.uk/datasets/ons::local-authority-district-to-region-december-2024-lookup-in-en/about
lad_to_region_census_2021_filename: "Local_Authority_District_to_Region_(December_2024)_Lookup_in_EN.csv"

# Postcode to OA (2021) to LSOA to MSOA to LAD (November 2024) Best Fit Lookup in the UK
# Link: https://open-geography-portalx-ons.hub.arcgis.com/datasets/068ee476727d47a3a7a0d976d4343c59/about
postcode_to_lad_census_2011_filename: "PCD_OA_LSOA_MSOA_LAD_NOV22_UK_LU.csv"

# Local Authority District to Region (April 2021) Lookup in EN
# Link: https://geoportal.statistics.gov.uk/datasets/ons::local-authority-district-to-region-april-2021-lookup-in-en/about
lad_to_region_census_2011_filename: "Local_Authority_District_to_Region_(April_2021)_Lookup_in_EN.xlsx"

### MCS EPC DATA ###

# MCS-EPC data up to Q1 2025 (date is the date of processing)
mcs_epc_filename_date: "250609"

# Fields in the MCS-EPC data that we're importing
relevant_mcs_epc_fields:
  [
    "original_mcs_index",
    "commission_date",
    "postcode",
    "tech_type",
    "cost",
    "cluster",
    "original_epc_index",
    "installation_type",
    "TOTAL_FLOOR_AREA",
    "CONSTRUCTION_AGE_BAND",
    "NUMBER_HABITABLE_ROOMS",
    "TENURE",
    "TRANSACTION_TYPE",
    "BUILT_FORM",
    "PROPERTY_TYPE",
    "INSPECTION_DATE",
  ]

### PROCESSING AND MODELLING CHOICES ###

# Threshold for the number of days between house built (info from EPC) and HP installed (info from MCS)
#for us to assume that HP was installed at the time of house build
hp_when_built_threshold: 365

# Exclusion criteria
exclusion_criteria:
  NUMBER_HABITABLE_ROOMS_lower_bound: 2
  TOTAL_FLOOR_AREA_lower_bound: 20
  TOTAL_FLOOR_AREA_upper_bound: 500
  PROPERTY_TYPE_allowed_list: ["House", "Bungalow"]

# winsorise
winsorise_outliers: "upper"

# Start date for MCS-EPC data
min_date: "2007-01-01"

# Model features - numeric and categorical
numeric_features: ["n_days", "TOTAL_FLOOR_AREA", "NUMBER_HABITABLE_ROOMS"]

# Categorical features to dummify
categorical_features_to_dummify:
  ["BUILT_FORM", "PROPERTY_TYPE", "CONSTRUCTION_AGE_BAND", "region_name"]

# Dummy features = since we have dummies, we don't need all of them (hence why some are commented out)
categorical_features: [
    "BUILT_FORM_detached",
    #'BUILT_FORM_end_terrace',
    "BUILT_FORM_mid_terrace",
    "BUILT_FORM_semi_detached",
    "PROPERTY_TYPE_bungalow",
    #'PROPERTY_TYPE_house',
    #'CONSTRUCTION_AGE_BAND_2007_onwards',
    "CONSTRUCTION_AGE_BAND_between_1930_1966",
    "CONSTRUCTION_AGE_BAND_between_1965_1983",
    "CONSTRUCTION_AGE_BAND_between_1983_2007",
    "CONSTRUCTION_AGE_BAND_pre_1929",
    "region_name_east_midlands",
    "region_name_east_of_england",
    "region_name_london",
    "region_name_north_east",
    "region_name_north_west",
    "region_name_scotland",
    "region_name_south_east",
    "region_name_south_west",
    "region_name_wales",
    #'region_name_yorkshire_and_the_humber',
    "region_name_west_midlands",
  ]

# Model target feature
target_feature: "cost"

# K-fold cross validation
kfold_splits: 5

# Date for comparing model performance in latest predictions
date_for_latest_predictions: "2023-01-01"

# Model hyperparameters
n_estimators: 450
min_samples_leaf: 100
min_samples_split: 10
random_state: 42
learning_rate: 0.2
max_depth: 5
